export const MARKER_START = '<!-- AI-TOKEN-OPTIMIZER:START -->';
export const MARKER_END = '<!-- AI-TOKEN-OPTIMIZER:END -->';
export const MARKER_COMMENT = '<!-- Generated by AI Token Optimizer extension. Do not edit between these markers. -->';

export const EXTENSION_ID = 'ai-token-optimize-claude';
export const EXTENSION_NAME = 'Token Optimizer for Claude & Copilot';

export const COPILOT_EXTENSION_ID = 'github.copilot';
export const CLAUDE_EXTENSION_ID = 'anthropic.claude-code';
export const CODEX_EXTENSION_ID = 'openai.codex';

// Install method for each tool
export type ToolInstallMethod = 'npm-global' | 'brew' | 'shell-script';

/**
 * Windows has neither Homebrew nor `curl | sh`, so tools that ship as a
 * release archive are downloaded and unpacked into the extension's managed bin
 * directory (see toolResolver.managedBinDir) via PowerShell.
 */
export interface WindowsDownload {
  /** Direct .zip URL — `releases/latest/download/...` avoids an API call. */
  zipUrl: string;
  /** Executable expected inside the archive, e.g. `rtk.exe`. */
  exeName: string;
}

export interface ToolInstallEntry {
  /** Binary name resolved via toolResolver (PATH + known install dirs) */
  name: string;
  description: string;
  method: ToolInstallMethod;
  /** npm package name (method: npm-global) */
  npmPackage?: string;
  /** Homebrew formula name (method: brew, macOS) */
  brewPackage?: string;
  /** curl install script URL fallback for non-macOS (method: brew falls back to this) */
  shellScriptUrl?: string;
  /** Prebuilt Windows archive — used instead of brew/shell on win32 */
  windowsDownload?: WindowsDownload;
  /** Args passed to the binary after a successful install */
  postInstallArgs?: string[];
}

// Real tools used by this extension:
//   codegraph: https://github.com/colbymchenry/codegraph   (@colbymchenry/codegraph on npm)
//   rtk:       https://github.com/rtk-ai/rtk               (Rust binary — brew install rtk)
export const TOOLS_TO_INSTALL: ToolInstallEntry[] = [
  {
    name: 'codegraph',
    description: 'Semantic code-graph indexing — 58% fewer AI tool calls, 22% faster answers (100% local)',
    method: 'npm-global',
    npmPackage: '@colbymchenry/codegraph',
    // post-install handled separately via offerWireAgents() (runs `codegraph install --yes`)
  },
  {
    name: 'rtk',
    description: 'CLI proxy — 60-90% token savings on git, test, build, ls, grep commands (Apache 2.0)',
    method: 'brew',
    brewPackage: 'rtk',
    shellScriptUrl: 'https://raw.githubusercontent.com/rtk-ai/rtk/refs/heads/master/install.sh',
    // Windows has no brew/sh — rtk publishes an x86_64 MSVC zip per release
    // (runs under emulation on arm64 Windows; no arm64 asset is published).
    windowsDownload: {
      zipUrl: 'https://github.com/rtk-ai/rtk/releases/latest/download/rtk-x86_64-pc-windows-msvc.zip',
      exeName: 'rtk.exe',
    },
    // Wires VS Code Copilot PreToolUse hook — transparent command rewrite, zero config
    postInstallArgs: ['init', '-g', '--copilot'],
  },
];

export const COPILOT_INSTRUCTIONS_PATH = '.github/copilot-instructions.md';
export const CLAUDE_INSTRUCTIONS_PATH = 'CLAUDE.md';
export const CODEX_INSTRUCTIONS_PATH = '.codex/instructions.md';

export const VERBOSITY_SAVINGS: Record<string, number> = {
  light: 20,
  full: 35,
  ultra: 50,
};

export const STRATEGY_DESCRIPTIONS = {
  codeGraph: 'CodeGraph pre-indexing — locate files via semantic query instead of grepping',
  outputCompression: 'RTK output compression — compress CLI/log output before AI reads it',
  verbosityControl: 'Caveman response control — constrain AI response length',
  sessionManagement: 'Session management — audit context, clear sessions, route models',
  semanticCache: 'Semantic cache — serve repeated/similar questions from local disk, zero tokens',
};

export const MCP_CACHE_SERVER_NAME = 'token-cache';

export const PROFILE_DESCRIPTIONS: Record<string, string> = {
  full: '$(zap) Full Optimization — all strategies active',
  debug: '$(bug) Debug Mode — output compression disabled for full logs',
  planning: '$(lightbulb) Planning Mode — verbosity control disabled for detailed analysis',
  review: '$(eye) Review Mode — session clearing disabled for full context',
  custom: '$(gear) Custom — manually selected strategies',
};
